valor = input("Digite o valor: ")
print(f'O valor digitado foi {valor}')
print(f'O valor digitado é {type(valor)}')
print(f'O valor digitado é numérico? {valor.isnumeric()}')
print(f'O valor digitado é alfabético? {valor.isalpha()}')
print(f'O valor digitado é alfanumérico? {valor.isalnum()}')
print(f'O valor digitado é maiúscula? {valor.isupper()}')
print(f'O valor digitado é minúscila? {valor.islower()}')
print(f'O valor digitado é capitalizado? {valor.istitle()}')